# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from config import google_api_key
gmaps.configure(api_key=google_api_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
city_data_file = "citydataclean.csv"

# Read the city data
city_data_clean = pd.read_csv(city_data_file)

# Display the data table for preview
city_data_clean.head()

,City,Country,City ID,Lat,Long,Max Temp,Humidity,Cloudiness,Wind Speed,Date
0,Bluff,NZ,2206939,-46.6000,168.3333,53.01,74,83,15.99,1615896086
1,Kovdor,RU,543508,67.5662,30.4758,27.00,89,100,8.19,1615896087
2,Kaitangata,NZ,2208248,-46.2817,169.8464,53.01,62,84,11.99,1615896088
3,Hobart,AU,2163355,-42.8794,147.3294,54.00,76,0,3.44,1615895933
4,Mataura,NZ,6201424,-46.1927,168.8643,53.01,74,70,15.99,1615896090

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Plot Heatmap
fig = gmaps.figure(map_type="HYBRID", center=(9.0778, 8.6775), zoom_level=1.8)

# Store latitude and longitude in locations
locations = city_data_clean[["Lat", "Long"]]

# Fill NaN values and convert to float
humidity = city_data_clean["Humidity"].astype(float)
max_humidity = city_data_clean["Humidity"].max()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max_humidity,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
temp_min = 83
temp_max = 87
windspeed_max = 10
windspeed_min = 4
cloudiness_max = 30

ideal_cities_df = city_data_clean.loc[((city_data_clean['Max Temp']>=temp_min) & 
                                   (city_data_clean['Max Temp']<=temp_max) & 
                                   (city_data_clean['Cloudiness']<=cloudiness_max)& 
                                   (city_data_clean['Wind Speed']>=windspeed_min)& 
                                   (city_data_clean['Wind Speed']<=windspeed_max)),:
                                  ].copy()

type(ideal_cities_df)

pandas.core.frame.DataFrame

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
ideal_cities_df

,City,Country,City ID,Lat,Long,Max Temp,Humidity,Cloudiness,Wind Speed,Date
111,Kharan,PK,1174062,28.5833,65.4167,85.95,11,25,7.31,1615896168
172,George Town,MY,1735106,5.4112,100.3354,86.00,66,20,5.75,1615896211
331,Roebourne,AU,2062276,-20.7833,117.1333,84.34,62,21,8.21,1615896331
377,Inyonga,TZ,159134,-6.7167,32.0667,83.50,47,5,5.21,1615896368
533,Dutlwe,BW,933787,-23.9833,23.9000,84.96,33,25,9.31,1615896489
548,Vila Velha,BR,3445026,-20.3297,-40.2925,84.00,69,20,9.22,1615896309
564,Adrar,MR,2381972,20.5022,-10.0711,85.64,10,0,9.55,1615896513
598,Tekkali,IN,1254794,18.6167,84.2333,83.84,57,0,8.12,1615896537
613,Okakarara,NaN,3354876,-20.5833,17.4333,84.16,37,26,5.99,1615896548
637,Tual,ID,1623197,-5.6667,132.7500,83.97,72,6,6.55,1615896566
667,Kulhudhuffushi,MV,1337613,6.6221,73.0700,84.31,64,2,9.62,1615896587
675,Sur,OM,286245,22.5667,59.5289,83.07,49,0,7.23,1615896592
712,Karratha,AU,6620339,-20.7377,116.8463,84.51,60,11,8.14,1615896625
753,Bloemhof,ZA,1018673,-27.6469,25.6070,83.30,29,18,9.73,1615896658
792,Opuwo,NaN,3354077,-18.0607,13.8400,84.83,40,20,7.11,1615896688
888,Alyangula,AU,2079582,-13.8483,136.4192,83.30,71,27,8.19,1615896759
917,Khorixas,NaN,3356213,-20.3667,14.9667,86.95,33,9,4.54,1615896780

In [6]:
ideal_cities_df['Hotel'] = ""
ideal_cities_df['Lat-Long'] = ideal_cities_df["Lat"].astype(str) +','+ ideal_cities_df["Long"].astype(str)

In [7]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "rankby": "distance",
    "type": "lodging",
    "key": google_api_key,
}
# use iterrows to iterate through pandas dataframe
for index, row in ideal_cities_df.iterrows():

    # get restaurant type from df
    location = row['Lat-Long']

    # add keyword to params dict
    params['location'] = location

    # assemble url and make API request
    #print(f"Retrieving Results for Index {index}: {location}.")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        
        ideal_cities_df.loc[index, 'Hotel'] = results[0]['name']

        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        ideal_cities_df.loc[index, 'Hotel'] = "no hotel found"
        
    print("------------")

Closest hotel is Dil Aram Bangla.
------------
Closest hotel is ZEN Rooms Victoria Street.
------------
Closest hotel is Victoria Hotel.
------------
Closest hotel is Eden Rock Lodge.
------------
Missing field/result... skipping.
------------
Closest hotel is Hostel da Prainha.
------------
Missing field/result... skipping.
------------
Closest hotel is Trinath Gantayat.
------------
Closest hotel is Okahitua, Omaboro City.
------------
Closest hotel is Jamrewav Family.
------------
Closest hotel is Asrafeege.
------------
Closest hotel is مجلس الشيخ / راشد سعيد علي المديلوي.
------------
Closest hotel is Karratha International Hotel.
------------
Closest hotel is Sleepers Guest House.
------------
Closest hotel is Ohakane Guesthouse.
------------
Closest hotel is SRA A Block.
------------
Closest hotel is iGowati Lodge.
------------

In [8]:
ideal_cities_df

,City,Country,City ID,Lat,Long,Max Temp,Humidity,Cloudiness,Wind Speed,Date,Hotel,Lat-Long
111,Kharan,PK,1174062,28.5833,65.4167,85.95,11,25,7.31,1615896168,Dil Aram Bangla,"28.5833,65.4167"
172,George Town,MY,1735106,5.4112,100.3354,86.00,66,20,5.75,1615896211,ZEN Rooms Victoria Street,"5.4112,100.3354"
331,Roebourne,AU,2062276,-20.7833,117.1333,84.34,62,21,8.21,1615896331,Victoria Hotel,"-20.7833,117.1333"
377,Inyonga,TZ,159134,-6.7167,32.0667,83.50,47,5,5.21,1615896368,Eden Rock Lodge,"-6.7167,32.0667"
533,Dutlwe,BW,933787,-23.9833,23.9000,84.96,33,25,9.31,1615896489,no hotel found,"-23.9833,23.9"
548,Vila Velha,BR,3445026,-20.3297,-40.2925,84.00,69,20,9.22,1615896309,Hostel da Prainha,"-20.3297,-40.2925"
564,Adrar,MR,2381972,20.5022,-10.0711,85.64,10,0,9.55,1615896513,no hotel found,"20.5022,-10.0711"
598,Tekkali,IN,1254794,18.6167,84.2333,83.84,57,0,8.12,1615896537,Trinath Gantayat,"18.6167,84.2333"
613,Okakarara,NaN,3354876,-20.5833,17.4333,84.16,37,26,5.99,1615896548,"Okahitua, Omaboro City","-20.5833,17.4333"
637,Tual,ID,1623197,-5.6667,132.7500,83.97,72,6,6.55,1615896566,Jamrewav Family,"-5.6667,132.75"
667,Kulhudhuffushi,MV,1337613,6.6221,73.0700,84.31,64,2,9.62,1615896587,Asrafeege,"6.6221,73.07"
675,Sur,OM,286245,22.5667,59.5289,83.07,49,0,7.23,1615896592,مجلس الشيخ / راشد سعيد علي المديلوي,"22.5667,59.5289"
712,Karratha,AU,6620339,-20.7377,116.8463,84.51,60,11,8.14,1615896625,Karratha International Hotel,"-20.7377,116.8463"
753,Bloemhof,ZA,1018673,-27.6469,25.6070,83.30,29,18,9.73,1615896658,Sleepers Guest House,"-27.6469,25.607"
792,Opuwo,NaN,3354077,-18.0607,13.8400,84.83,40,20,7.11,1615896688,Ohakane Guesthouse,"-18.0607,13.84"
888,Alyangula,AU,2079582,-13.8483,136.4192,83.30,71,27,8.19,1615896759,SRA A Block,"-13.8483,136.4192"
917,Khorixas,NaN,3356213,-20.3667,14.9667,86.95,33,9,4.54,1615896780,iGowati Lodge,"-20.3667,14.9667"

In [15]:
type(ideal_cities_df)

pandas.core.frame.DataFrame

In [16]:
ideal_cities_df = ideal_cities_df.loc[ideal_cities_df["Hotel"]!= "no hotel found"]

In [17]:
ideal_cities_df

,City,Country,City ID,Lat,Long,Max Temp,Humidity,Cloudiness,Wind Speed,Date,Hotel,Lat-Long
111,Kharan,PK,1174062,28.5833,65.4167,85.95,11,25,7.31,1615896168,Dil Aram Bangla,"28.5833,65.4167"
172,George Town,MY,1735106,5.4112,100.3354,86.00,66,20,5.75,1615896211,ZEN Rooms Victoria Street,"5.4112,100.3354"
331,Roebourne,AU,2062276,-20.7833,117.1333,84.34,62,21,8.21,1615896331,Victoria Hotel,"-20.7833,117.1333"
377,Inyonga,TZ,159134,-6.7167,32.0667,83.50,47,5,5.21,1615896368,Eden Rock Lodge,"-6.7167,32.0667"
548,Vila Velha,BR,3445026,-20.3297,-40.2925,84.00,69,20,9.22,1615896309,Hostel da Prainha,"-20.3297,-40.2925"
598,Tekkali,IN,1254794,18.6167,84.2333,83.84,57,0,8.12,1615896537,Trinath Gantayat,"18.6167,84.2333"
613,Okakarara,NaN,3354876,-20.5833,17.4333,84.16,37,26,5.99,1615896548,"Okahitua, Omaboro City","-20.5833,17.4333"
637,Tual,ID,1623197,-5.6667,132.7500,83.97,72,6,6.55,1615896566,Jamrewav Family,"-5.6667,132.75"
667,Kulhudhuffushi,MV,1337613,6.6221,73.0700,84.31,64,2,9.62,1615896587,Asrafeege,"6.6221,73.07"
675,Sur,OM,286245,22.5667,59.5289,83.07,49,0,7.23,1615896592,مجلس الشيخ / راشد سعيد علي المديلوي,"22.5667,59.5289"
712,Karratha,AU,6620339,-20.7377,116.8463,84.51,60,11,8.14,1615896625,Karratha International Hotel,"-20.7377,116.8463"
753,Bloemhof,ZA,1018673,-27.6469,25.6070,83.30,29,18,9.73,1615896658,Sleepers Guest House,"-27.6469,25.607"
792,Opuwo,NaN,3354077,-18.0607,13.8400,84.83,40,20,7.11,1615896688,Ohakane Guesthouse,"-18.0607,13.84"
888,Alyangula,AU,2079582,-13.8483,136.4192,83.30,71,27,8.19,1615896759,SRA A Block,"-13.8483,136.4192"
917,Khorixas,NaN,3356213,-20.3667,14.9667,86.95,33,9,4.54,1615896780,iGowati Lodge,"-20.3667,14.9667"

In [21]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_map = [info_box_template.format(**row) for index, row in ideal_cities_df.iterrows()]
locations = ideal_cities_df[['Lat','Long']]

In [27]:
hotel_map

['\n<dl>\n<dt>Name</dt><dd>Dil Aram Bangla</dd>\n<dt>City</dt><dd>Kharan</dd>\n<dt>Country</dt><dd>PK</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>ZEN Rooms Victoria Street</dd>\n<dt>City</dt><dd>George Town</dd>\n<dt>Country</dt><dd>MY</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Victoria Hotel</dd>\n<dt>City</dt><dd>Roebourne</dd>\n<dt>Country</dt><dd>AU</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Eden Rock Lodge</dd>\n<dt>City</dt><dd>Inyonga</dd>\n<dt>Country</dt><dd>TZ</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Hostel da Prainha</dd>\n<dt>City</dt><dd>Vila Velha</dd>\n<dt>Country</dt><dd>BR</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Trinath Gantayat</dd>\n<dt>City</dt><dd>Tekkali</dd>\n<dt>Country</dt><dd>IN</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Okahitua, Omaboro City</dd>\n<dt>City</dt><dd>Okakarara</dd>\n<dt>Country</dt><dd>nan</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Jamrewav Family</dd>\n<dt>City</dt><dd>Tual</dd>\n<dt>Country</dt><dd>ID</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Asrafeege</dd>\n<dt>City</dt><dd>Kulhudhuffushi</dd>\n<dt>Country</dt><dd>MV</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>مجلس الشيخ / راشد سعيد علي المديلوي</dd>\n<dt>City</dt><dd>Sur</dd>\n<dt>Country</dt><dd>OM</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Karratha International Hotel</dd>\n<dt>City</dt><dd>Karratha</dd>\n<dt>Country</dt><dd>AU</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Sleepers Guest House</dd>\n<dt>City</dt><dd>Bloemhof</dd>\n<dt>Country</dt><dd>ZA</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>Ohakane Guesthouse</dd>\n<dt>City</dt><dd>Opuwo</dd>\n<dt>Country</dt><dd>nan</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>SRA A Block</dd>\n<dt>City</dt><dd>Alyangula</dd>\n<dt>Country</dt><dd>AU</dd>\n</dl>\n',
 '\n<dl>\n<dt>Name</dt><dd>iGowati Lodge</dd>\n<dt>City</dt><dd>Khorixas</dd>\n<dt>Country</dt><dd>nan</dd>\n</dl>\n']

In [30]:
# Display previously created heatmap
fig

# Display figure

Figure(layout=FigureLayout(height='420px'))